# softmax函数解析

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable

# Cross entropy example
import numpy as np

# One hot
# 0: 1 0 0
# 1: 0 1 0
# 2: 0 0 1
Y = np.array([1, 0, 0])

Y_pred1 = np.array([0.7, 0.2, 0.1])
Y_pred2 = np.array([0.1, 0.3, 0.6])
print("loss1 = ", np.sum(-Y * np.log(Y_pred1)))
print("loss2 = ", np.sum(-Y * np.log(Y_pred2)))

# Softmax + CrossEntropy (logSoftmax + NLLLoss)
loss = nn.CrossEntropyLoss()

loss1 =  0.35667494393873245
loss2 =  2.3025850929940455


/Users/bruce/anaconda3/envs/pytorch/lib/python3.6/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:

# target is of size nBatch
# each element in target has to have 0 <= value < nClasses (0-2)
# Input is class, not one-hot
Y = Variable(torch.LongTensor([0]), requires_grad=False)

# input is of size nBatch x nClasses = 1 x 4
# Y_pred are logits (not softmax)
Y_pred1 = Variable(torch.Tensor([[2.0, 1.0, 0.1]]))
Y_pred2 = Variable(torch.Tensor([[0.5, 2.0, 0.3]]))

l1 = loss(Y_pred1, Y)
l2 = loss(Y_pred2, Y)

print("PyTorch Loss1 = ", l1.data, "\nPyTorch Loss2=", l2.data)

print("Y_pred1=", torch.max(Y_pred1.data, 1)[1])
print("Y_pred2=", torch.max(Y_pred2.data, 1)[1])

PyTorch Loss1 =  tensor(0.4170) 
PyTorch Loss2= tensor(1.8406)
Y_pred1= tensor([0])
Y_pred2= tensor([1])


In [4]:
# target is of size nBatch
# each element in target has to have 0 <= value < nClasses (0-2)
# Input is class, not one-hot
Y = torch.LongTensor([2, 0, 1])

# input is of size nBatch x nClasses = 2 x 4
# Y_pred are logits (not softmax)
Y_pred1 = torch.Tensor([[0.1, 0.2, 0.9], [1.1, 0.1, 0.2], [0.2, 2.1, 0.1]])

Y_pred2 = torch.Tensor([[0.8, 0.2, 0.3], [0.2, 0.3, 0.5], [0.2, 0.2, 0.5]])

l1 = loss(Y_pred1, Y)
l2 = loss(Y_pred2, Y)

print("Batch Loss1 = ", l1.data, "\nBatch Loss2=", l2.data)
a = np.array([[1, 2, 3], [2, 4, 5]])
b = torch.from_numpy(a)
print(b.max(1))

Batch Loss1 =  tensor(0.4966) 
Batch Loss2= tensor(1.2389)
torch.return_types.max(
values=tensor([3, 5]),
indices=tensor([2, 2]))


In [5]:
linear = torch.nn.Linear(32, 2)

In [6]:
inputs = torch.rand(3, 32)

In [7]:
outputs = linear(inputs)

In [8]:
outputs

tensor([[-0.3624, -0.3677],
        [-0.0308, -0.1978],
        [-0.0444, -0.1296]], grad_fn=<AddmmBackward0>)

In [9]:
activation = F.sigmoid(outputs)

/Users/bruce/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:1806: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


In [10]:
activation

tensor([[0.4104, 0.4091],
        [0.4923, 0.4507],
        [0.4889, 0.4677]], grad_fn=<SigmoidBackward0>)

In [11]:
F.softmax(outputs)

/Users/bruce/anaconda3/envs/pytorch/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([[0.5013, 0.4987],
        [0.5417, 0.4583],
        [0.5213, 0.4787]], grad_fn=<SoftmaxBackward0>)

In [12]:
F.relu(outputs)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], grad_fn=<ReluBackward0>)

In [13]:
a1 = torch.tensor([1.,2.,3.])

In [14]:
F.softmax(a1)

/Users/bruce/anaconda3/envs/pytorch/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([0.0900, 0.2447, 0.6652])